services:
  api:
    # restart: always
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: 'fastapi-reminder'
    working_dir: '/api'
    tty: true
    stdin_open: true
    volumes:
      - ./:/api
    # command: ls
    ports:
      - "5001:5000"
      - "5678:5678"

    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: 'db-reminder'
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: 'minio-reminder'
    hostname: 'minio'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: 'minio'
      MINIO_ROOT_PASSWORD: 'password'
    entrypoint: sh
    command: -c "/usr/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
      - minio_data:/var/lib/minio/data

volumes:
  postgres_data:
  minio_data:

      



